config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'search#index', as: :root

  get 'bookcases/new', to: 'bookcases#new', as: :new_bookcase
  post 'bookcases', to: 'bookcases#create', as: :bookcases
  delete 'bookcases/:id', to: 'bookcases#destroy', as: :bookcase

  get 'books/new', to: 'books#new', as: :new_book
  post 'books', to: 'books#create', as: :books
  delete 'books/:id', to: 'books#destroy', as: :book
  patch 'books/:id', to: 'books#update'

end

app/models/book.rb
class Book < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true
  validates :author, presence: true
  belongs_to :bookcase
end

app/models/bookcase.rb
class Bookcase < ActiveRecord::Base

  validates :name, presence: true
  validates :description, presence: true
  has_many :books, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookcases_controller.rb
class BookcasesController < ApplicationController

  def new
    @bookcase = Bookcase.new
    @bookcases = Bookcase.all
  end

  def create
    @bookcase = Bookcase.new(name: params[:name], description: params[:description])
    if @bookcase.save
      redirect_to  new_bookcase_path, notice: "The Bookcase was added!"
    else
      @bookcases = Bookcase.all
      render :new
    end
  end

  def destroy
    @bookcase = Bookcase.find(params[:id])
    @bookcase.destroy
    redirect_to new_bookcase_path, notice: "The Bookcase was deleted"
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
    @books = Book.all
    @bookcases = Bookcase.all
  end

  def create
    @book = Book.new(name: params[:name], author: params[:author], bookcase_id: params[:bookcase_id], row: params[:row], position: params[:position], section: params[:section], orientation: params[:orientation])
    if @book.save
      redirect_to new_book_path, notice: "The Book was added!"
    else
      @books = Book.all
      @bookcases = Bookcase.all
      render :new
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.status
      @book.status = false
    else
      @book.status = true
    end
    @book.save
    redirect_to root_path
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to new_book_path, notice: "The Book was deleted"
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    if params[:query].present?
      @books = Book.where("name ILIKE ?", "%#{params[:query]}%")
      if @books.empty?
        flash[:notice] = "Book was not found. Try again"
      end
    else
      @books = Book.all.order(:name)
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookcases/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-9">
      <h1 class="text-center">Add Bookcase</h1>

      <% if @bookcase.errors.any? %>
        <ul class="list-unstyled">
          <% @bookcase.errors.each do |column, message| %>
            <div class="row">
              <li class="col-lg-6 col-lg-offset-3 text-center alert alert-danger">
                <%= column.capitalize %> <%= message %>
              </li>
            </div>
          <% end %>
      <% end %>

      <%= form_tag bookcases_path, class: "form-horizontal" do %>
        <div class="form-group">
          <div class="col-lg-3 col-lg-offset-3 text-center">
            <%= label_tag :name %>
          </div>
          <%= text_field_tag :name, @bookcase.name, placeholder: "name"  %>
        </div>
        <div class="form-group">
          <div class="col-lg-3 col-lg-offset-3 text-center">
            <%= label_tag :description %>
          </div>
          <%= text_area_tag :description, @bookcase.description, placeholder: "description" %>
        </div>
        <div class="col-lg-2 col-lg-offset-5">
          <%= submit_tag "Add", class: "btn btn-block btn-success"  %>
        </div>
      <% end %>
    </div>

    <div class="col-md-3">
        <% if @bookcases %>
          <% @bookcases.each do |bookcase| %>
            <div class="list row">
              <ul class="list-unstyled col-md-10">
                <li><h4><%= bookcase.name %></h4></li>
                <li><%= bookcase.description %></li>
              </ul>
              <%= form_tag bookcase_path(bookcase.id), method: "DELETE", class: 'col-md-2' do %>
                <%= submit_tag "X", data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
              <% end %>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>

</div>

app/views/books/new.html.erb
<div class="container">

  <div class="row">
    <div class="col-md-9">
      <h1 class="text-center">Add Book</h1>

      <% if @book.errors.any? %>
        <ul class="list-unstyled">
          <% @book.errors.each do |column, message| %>
            <div class="row">
              <li class="col-lg-6 col-lg-offset-3 text-center alert alert-danger">
                <%= column.capitalize %> <%= message %>
              </li>
            </div>
          <% end %>
      <% end %>

      <%= form_tag books_path, class: "form-horizontal" do %>
        <div class="form-group">
          <div class="col-lg-3 col-lg-offset-3 text-center">
            <%= label_tag :name %>
          </div>
          <%= text_field_tag :name, @book.name, placeholder: "name"  %>
        </div>
        <div class="form-group">
          <div class="col-lg-3 col-lg-offset-3 text-center">
            <%= label_tag :author %>
          </div>
          <%= text_field_tag :author, @book.author, placeholder: "author" %>
        </div>
        <div class="form-group">
          <div class="col-lg-3 col-lg-offset-3 text-center">
            <%= label_tag :bookcase_id %>
          </div>
          <%= select_tag "bookcase_id", options_from_collection_for_select(@bookcases, :id, :name) %>
        </div>
        <div class="form-group">
          <div class="col-lg-3 col-lg-offset-3 text-center">
            <%= label_tag :row %>
          </div>
          <%= select_tag "row", options_for_select(1..4) %>
        </div>
        <div class="form-group">
          <div class="col-lg-3 col-lg-offset-3 text-center">
            <%= label_tag :position %>
          </div>
          <%= select_tag "position", options_for_select(1..10) %>
        </div>
        <div class="form-group">
          <div class="col-lg-3 col-lg-offset-3 text-center">
            <%= label_tag :section %>
          </div>
          <%= select_tag "section", options_for_select(1..5) %>
        </div>
        <div class="form-group">
          <div class="col-lg-3 col-lg-offset-3 text-center">
            <%= label_tag :orientation %>
          </div>
          <%= select_tag "orientation", options_for_select(["horizontal", "vertical"]) %>
        </div>
        <div class="col-lg-2 col-lg-offset-5">
          <%= submit_tag "Add", class: "btn btn-block btn-success"  %>
        </div>
      <% end %>
    </div>

    <div class="col-md-3">
        <% if @books %>
          <% @bookcases.each do |bookcase| %>
            <div class="list">
              <ul class="list-unstyled">
                <li><h4><%= bookcase.name %></h4></li>
                <% bookcase.books.each do |book| %>
                  <div class="list row">
                    <ul class="list-unstyled col-md-10">
                      <li><em><%= book.name.capitalize %></em> by <%= book.author.capitalize %></li>
                    </ul>
                    <%= form_tag book_path(book.id), method: "DELETE", class: 'col-md-2' do %>
                      <%= submit_tag "X", data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
                    <% end %>
                  </div>
                <% end %>
              </ul>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Archives</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
        <%= link_to image_tag("logo.png", class: "navbar-brand"), root_path %>
        <%= link_to "Add Bookcase", new_bookcase_path, class: "navbar-brand"  %>
        <%= link_to "Add Book", new_book_path, class: "navbar-brand"  %>
      </div>
      <div class="navbar-right">
        <%= link_to "Sign In", "#", class: "navbar-brand" %>
      </div>
    </div>
  </nav>

  <% if flash[:notice] %>
    <div class="col-lg-6 col-lg-offset-3 text-center alert alert-info flash">
      <%= flash[:notice] %>
    </div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/search/index.html.erb
<div class="container">

  <%= form_tag root_path, class: "form-inline", method: "GET" do %>
    <div class="text-center">
      <div class="form-group">
        <%= text_field_tag :query, params[:query], placeholder: "Harry Potter", class: "form-control" %>
      </div>
      <%= submit_tag "Search", class: "btn btn-default" %>
    </div>
  <% end %>

  <table class="table table-bordered" id="books">
    <thead>
      <tr>
        <th colspan="8" class="text-center"><h3>Current Books</h3></th>
      </tr>
      <tr>
        <th class="text-center sort" id="name">Name (sort)</th>
        <th class="text-center">Author</th>
        <th class="text-center sort" id="bookcase">Bookcase (sort)</th>
        <th class="text-center">Row</th>
        <th class="text-center">Position</th>
        <th class="text-center">Section</th>
        <th class="text-center">Orientation</th>
        <th class="text-center">In/out</th>
      </tr>
    </thead>

    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.name %></td>
          <td><%= book.author %></td>
          <td><%= book.bookcase.name %></td>
          <td><%= book.row %></td>
          <td><%= book.position %></td>
          <td><%= book.section %></td>
          <td><%= book.orientation %></td>
          <% if book.status %>
            <td>
              <%= form_tag book_path(book.id), method: "PATCH" do %>
                <%= submit_tag "Take out", class: "btn btn-success" %>
              <% end %>
            </td>
          <% else %>
            <td>
              <%= form_tag book_path(book.id), method: "PATCH" do %>
                <%= submit_tag "Put back", class: "btn btn-info" %>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>